image: node:latest

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - set http_proxy=http://registry.npmjs.org/
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
  dependencies:
    - install

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cp build/index.html build/404.html
    - mv build/* public
  artifacts:
    paths:
      - public
